name: Terraform CI

on:
  pull_request:
    paths:
      - '**/*.tf'  # Trigger only for Terraform files

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.0 

    - name: Terraform Format (fmt)
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan